// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Training.DataAccess;

#nullable disable

namespace Training.DataAccess.Migrations
{
    [DbContext(typeof(TrainingDbContext))]
    [Migration("20241031050845_addingDB")]
    partial class addingDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trainingtask.Models.Entity.Company", b =>
                {
                    b.Property<string>("ComId")
                        .HasColumnType("text")
                        .HasColumnName("comid");

                    b.Property<decimal>("Basic")
                        .HasColumnType("numeric")
                        .HasColumnName("basic");

                    b.Property<string>("ComName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comname");

                    b.Property<decimal>("Hrent")
                        .HasColumnType("numeric")
                        .HasColumnName("hrent");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("boolean")
                        .HasColumnName("isinactive");

                    b.Property<decimal>("Medical")
                        .HasColumnType("numeric")
                        .HasColumnName("medical");

                    b.HasKey("ComId")
                        .HasName("pk_companies");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Trainingtask.Models.Entity.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("upby")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("upby");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Trainingtask.Models.Entity.Designation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("upby")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("upby");

                    b.HasKey("Id")
                        .HasName("pk_designations");

                    b.ToTable("designations", (string)null);
                });

            modelBuilder.Entity("Trainingtask.Models.Entity.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("DeptId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deptid");

                    b.Property<string>("DesigId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("desigid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("upby")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("upby");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("DeptId")
                        .HasDatabaseName("ix_employees_deptid");

                    b.HasIndex("DesigId")
                        .HasDatabaseName("ix_employees_desigid");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Trainingtask.Models.Entity.Shift", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("shiftid");

                    b.Property<string>("ComId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("In")
                        .HasColumnType("interval")
                        .HasColumnName("in");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<TimeSpan>("Late")
                        .HasColumnType("interval")
                        .HasColumnName("late");

                    b.Property<TimeSpan>("Out")
                        .HasColumnType("interval")
                        .HasColumnName("out");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shiftname");

                    b.Property<string>("upby")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("upby");

                    b.HasKey("ShiftId")
                        .HasName("pk_shifts");

                    b.HasIndex("ComId")
                        .HasDatabaseName("ix_shifts_comid");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("Trainingtask.Models.Entity.Employee", b =>
                {
                    b.HasOne("Trainingtask.Models.Entity.Department", "Dept")
                        .WithMany("Employees")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employees_departments_deptid");

                    b.HasOne("Trainingtask.Models.Entity.Designation", "Desig")
                        .WithMany("Employees")
                        .HasForeignKey("DesigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employees_designations_desigid");

                    b.Navigation("Dept");

                    b.Navigation("Desig");
                });

            modelBuilder.Entity("Trainingtask.Models.Entity.Shift", b =>
                {
                    b.HasOne("Trainingtask.Models.Entity.Company", "Company")
                        .WithMany("Shifts")
                        .HasForeignKey("ComId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shifts_companies_comid");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Trainingtask.Models.Entity.Company", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Trainingtask.Models.Entity.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Trainingtask.Models.Entity.Designation", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
